
# makefile for counting the occurence of the number in the given array

CC=g++
CFLAGS=-g -Wall
all: numberOccur

numberOccur: numberOccur.cc 
	$(CC) $(CFLAGS) -o numberOccur.o numberOccur.cc

clean:
	rm numberOccur.o