
# makefile for drawing a square 10x10 on the terminal

CC=g++
CFLAGS=-g -Wall
all: bitManipulate

bitManipulate: bitManipulate.cc
	$(CC) $(CFLAGS) -o bitManipulate.o bitManipulate.cc 

clean:
	rm bitManipulate.o