
# makefile for checking a char is a digit, a hex-digit or not

CC=g++
CFLAGS=-g -Wall
all: checkDigit

checkDigit: checkDigit.cc 
	$(CC) $(CFLAGS) -o checkDigit.o checkDigit.cc 

clean:
	rm checkDigit.o 