
# makefile for counting number of posotive and negative values program

CC=g++
CFLAGS=-g -Wall
all: countPosNeg

countPosNeg: countPosNeg.cc
	$(CC) $(CFLAGS) -o countPosNeg.o countPosNeg.cc

clean:
	rm countPosNeg.o