
# A file making for date arithmatic program

CC=g++
CFLAGS=-g -Wall
all: dateArithmetic

dateArithmetic: dateArithmetic.cc
				$(CC) $(CFLAGS) -o dateArithmetic.o dateArithmetic.cc

clean:
				rm dateArithmetic.o