
# makefile for replacing char '-' with '_' in a given string

CC=g++
CFLAGS=-g -Wall
all: replaceChar

replaceChar: replaceChar.cc 
	$(CC) $(CFLAGS) -o replaceChar.o replaceChar.cc 

clean:
	rm replaceChar.o