
# makefile for counting number of set bit in given integer program

CC=g++
CFLAGS=-g -Wall
all: countSetBit

countSetBit: countSetBit.cc 
	$(CC) $(CFLAGS) -o countSetBit.o countSetBit.cc

clean:
	rm countSetBit.o

run:
	./countSetBit.o