
# makefile for  printing the multiplication table

CC=g++
CFLAGS=-g -Wall
all: multiplicationTable

multiplicationTable: multiplicationTable.cc 
	$(CC) $(CFLAGS) -o multiplicationTable.o multiplicationTable.cc 

clean:
	rm multiplicationTable.o