
# makefile for printing a square check board program

CC=g++
CFLAGS=-g -Wall
all: printCheckboard

printCheckboard: printCheckboard.cc
	$(CC) $(CFLAGS) -o printCheckboard.o printCheckboard.cc 

clean:
	rm printCheckboard.o