
# makefile for calculating the average for a float series

CC=g++
CFLAGS=-g -Wall
all: averageNumber

averageNumber: averageNumber.cc
	$(CC) $(CFLAGS) -o averageNumber.o averageNumber.cc 

clean:
	rm averageNumber.o