
# makefile for calculating total resistor of parallel resistors

CC=g++
CFLAGS=-g -Wall
all: totalParallelResistor

totalParallelResistor: totalParallelResistor.cc
	$(CC) $(CFLAGS) -o totalParallelResistor.o totalParallelResistor.cc

clean:
	rm totalParallelResistor.o