
# makefile for checking if the input value is divisible by 10

CC=g++
CFLAGS=-g -Wall
all: divisible10

divisible10: divisible10.cc 
	$(CC) $(CFLAGS) -o divisible10.o divisible10.cc

clean:
	rm divisible10.o