
# makefile for Time transfer file program

CC=g++
CFLAGS=-g -Wall
all: timeTransferFile

timeTransferFile: timeTransferFile.cc
								$(CC) $(CFLAGS) -o timeTransferFile.o timeTransferFile.cc

clean:
								rm timeTransferFile.o