
# makefile for checking whether a given character is a vowel, a consonant or not in 
# alphabet

CC=g++
CFLAGS=-g -Wall
all: checkLetter

checkLetter: checkLetter.cc 
	$(CC) $(CFLAGS) -o checkLetter.o checkLetter.cc 

clean:
	rm checkLetter.o
