
# makefile for checking if the first string begins the second

CC=g++
CFLAGS=-g -Wall
all: beginString

beginString: beginString.cc
	$(CC) $(CFLAGS) -o beginString.o beginString.cc

clean:
	rm beginString.o